[package]
name = "cognitive_processor_unit"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["json", "blocking"] }
serde =  { version = "1.0.228", features = ["derive"] }

